version: '3'

services:
  

  weather_backend:
    image: backend
    volumes: 
      - ./backend:/usr/src/app
    ports:
      - 9000:9000
    environment:
      - APPID=${APPID}
  weather_frontend:
    image: frontend
    volumes:
        - ./frontend:/usr/src/app
    ports:
      - 8000:8000
   